### PR TITLE
Add extension group support

### PR DESCRIPTION
**Pull request by matzipan**
Related to #3 

- [x] Add test

Still missing "all" and "choice"  (#20).

### CODE REVIEW

**Comment by matzipan** [comment]
I don't really like this implementation. A nicer one would get the fields for the target struct and create a list instead of just a reference (same for the extension base). But I wasn't sure how to reach that so if you have any suggestions, it's welcome. Maybe a two-pass implementation?

**Comment by matzipan** [comment]
@MarcAntoine-Arnaud  do you think there's any path to get this merged? If not, could you please comment on what adjustments I should make.

**Review by MarcAntoine-Arnaud — APPROVED** [review]

**Comment by MarcAntoine-Arnaud** [comment]
Sorry more time was needed to understand your code.
I have review it and merged.

Thank you !

**Comment by matzipan** [comment]
Sorry my comment was not meant as pressure - I just wanted to get a rough idea.

**Pull request merged**
